### ISSUE TITLE
meta.xls file cannot be found

### ISSUE THREAD

**Issue by kaltinel** [qinqian/lisa#1]
I am trying to use LISA with my large gene lists. However, I am encountering many errors in the way.
I am trying to run it with :
`lisa_model --sample_number 1 --species hg38 --gene_set /home/data/genename_FC12_DE_DOWN.txt --foreground None --background None --prefix=/home/data --new_h5=None --covariates=None --only_newhdf5=None`

And I am receiving an error of : 
```
File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'${prefix}/lisa_meta.xls' does not exist

```

I see that under `lisa/demo` there are `xml `files premade ( such as `lisa_results_meta_table_human_with_gene_sets.xls` ) . I tried to point this file in prefix, and also created an empty `lisa_meta.xls` file, none of them worked.

I would appreciate the help, thanks!

**Comment by qinqian** [comment]
Hi Kaltinel, It seems that your configuration was not updated. Could you try the following commands: 

wget --user=lisa --password='xxx'  http://lisa.cistrome.org/cistromedb_data/lisa_v1.0_hg38.tar.gz
tar xvfz lisa_v1.0_hg38.tar.gz
lisa_update_conf --folder hg38/ --species hg38

The lisa_meta.xls is located in the hg38/ path. Those lisa_results_meta_table_human_with_gene_sets.xls are the benchmark expression profiles we used in the paper. You can use the demo/AR.symbol to test the installation first.

**Comment by kaltinel** [comment]
Thank you very much for your reply- I am installing the new files.

Will I need to specify the prefix to the /hg38/ (as a path of  lisa_meta.xls) ?

**Comment by qinqian** [comment]
Yes, please use the absolute path to /hg38/, the lisa_update_conf script will automatically fill in all the configuration information for you.
