### ISSUE TITLE
Interpretation for LISA results

### ISSUE THREAD

**Issue by ziyili20** [qinqian/lisa#3]
Hello, I have been using LISA recently and found it very helpful. However, it is not clear to me what this "1st sample", "2nd sample", etc. means. Are they referring to different ChIP-seq data sources? Which sample I should look at? 
I carefully read the software manual. But it is not explained in that manual either.

**Comment by qinqian** [comment]
Thanks for your feedback! The 1st sample, 2nd sample, etc. means the ChIP-seq samples for the same transcriptional regulators, we should look at the first sample with the lowest p-value. I will add documentation to explain this detail.

**Comment by ziyili20** [comment]
Thank you very much for the helpful explanations!
