### ISSUE TITLE
conda search lisa

### ISSUE THREAD

**Issue by ChangliangWang** [qinqian/lisa#4]
Dear qin,

I used conda search lisa to search lisa. However, I can't find the tool. Do you have some recommedations for finding the tool and installing it? (When creating the env named lisa, I just used 'conda create -n lisa'. My python version is 2.7.18.)

![image](https://user-images.githubusercontent.com/25944188/91537159-6a62d300-e948-11ea-84a9-04b7f126ad18.png)

Thanks very much for your help.

Best wishes,
Changliang.

**Comment by qinqian** [comment]
Hi Changliang, 

The reason why you cannot search lisa because it is not in the default channel, the channel is specify by using the option -c. The python versions tested are 3.6.5, 3.6.6 and 3.6.7. 

Could you please try the following command to install Lisa? 

```
conda config --add channels defaults && conda config --add channels conda-forge && conda config --add channels bioconda && conda install mamba -c conda-forge && mamba create -n lisa -c qinqian lisa=1.0 python=3.6.6. 
```

or 

```
conda config --add channels defaults && conda config --add channels conda-forge && conda config --add channels bioconda && conda install mamba -c conda-forge && mamba create -n lisa -c qinqian lisa_minimal python=3.6.6. 
```

Best,
Qian Qin

**Comment by ChangliangWang** [comment]
Dear Qian,

Using the command you recommended, I got the below error, which seems to be a network error. Do you know how to solve this problem.

Thanks very much for your help.

Best wishes,
Changliang.

________________________________
发件人: Qian Alvin Qin <notifications@github.com>
发送时间: 2020年8月29日 5:52
收件人: qinqian/lisa <lisa@noreply.github.com>
抄送: Wang Changliang <yb67610@connect.um.edu.mo>; Author <author@noreply.github.com>
主题: Re: [qinqian/lisa] conda search lisa (#4)


Hi Changliang,

The reason why you cannot search lisa because it is not in the default channel, the channel is specify by using the option -c. The python versions tested are 3.6.5, 3.6.6 and 3.6.7.

Could you please try the following command to install Lisa?

conda config --add channels defaults && conda config --add channels conda-forge && conda config --add channels bioconda && conda install mamba -c conda-forge && mamba create -n lisa -c qinqian lisa=1.0 python=3.6.6.


or

conda config --add channels defaults && conda config --add channels conda-forge && conda config --add channels bioconda && conda install mamba -c conda-forge && mamba create -n lisa -c qinqian lisa_minimal python=3.6.6.


Best,
Qian Qin

―

**Comment by qinqian** [comment]
Hi Changliang, 

I cannot see the error log, could you please upload the log again? Are you using Linux or osx?

Best,
Qian

**Comment by ChangliangWang** [comment]
Hi Qian,

I have attached my error. I am using linux!

![image](https://user-images.githubusercontent.com/25944188/91625570-076e4c00-e9db-11ea-9a83-d60ce468656a.png)


Thanks very much for your help.

Best wishes，
Changliang.

**Comment by qinqian** [comment]
Hi Changliang, 

I see. Can you access https://anaconda.org/? It seems that the network has been blocked to access anaconda channels. Perhaps you could use a VPN to access anaconda packages. 

Best, 
Qian Qin

**Comment by ChangliangWang** [comment]
Hi Qian,

Thanks very much for your recommendation. I have dowloaded lisa-1.0-py36h14c3975_8.tar.bz2 from anaconda with the help of VPN. Then, I have created an env by 'conda create -n lisa python=3.6' and then install lisa using 'conda install lisa-1.0-py36h14c3975_8.tar.bz2'. When I try to install 'yaml' for the env, it sait that ' lisa-1.0-py36h14c3975_8 is causing the inconsistency'. Have you ever encountered this problem? 

Sorry to bother you again.
Thanks very much for your help.

Best wishes,
Changliang.

**Comment by ChangliangWang** [comment]
Hi Qian,

When I update lisa, the setup.py needs the numpy=1.15.1. However, when it install 'pandas', which said that it need at least 'numpy=1.15.4'. Could you tell me which version of 'pandas' you used? 

Thanks very much for your help.

Best wishes,
Changliang.

**Comment by ChangliangWang** [comment]
I used 'pandas=0.23.4' and I have modified the 33th line and 35 line of 'setup.py' by adding a '#' to 'numpy=1.15.1' and 'pandas'.   and then manually installed the two packages in above-mentioned version. Finally, I have successfully installed it. Thanks.

**Comment by qinqian** [comment]
Hi Changliang, 

Thanks you a lot for your exploration! I've never seen such a problem before, I'll add in the Readme.

The version I have successfully deployed for the two packages includes: numpy 1.15.1 with pandas 0.25.2, numpy 1.15.1 with pandas 1.0.5, numpy 1.17.2 with pandas 1.0.5. 

Best wishes,
Qian Qin
