### ISSUE TITLE
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

### ISSUE THREAD

**Issue by ChangliangWang** [qinqian/lisa#5]
Hi Qian,

When I running lisa, I encountered the above problem. The error is caused by that 'lbfgs' solver doesn't support l1 penalty ('liblinear' solver supports l1 penalty). Have you ever encountered this problem and how did you fix it?

Thanks very much for your help.

Best wishes,
Changliang.

**Comment by qinqian** [comment]
Hi Changliang, 

Yes, we've encountered such a problem before, could you try to downgrade the sklearn version to 0.21.3? 

Best,
Qian

**Comment by ChangliangWang** [comment]
Hi Qian,

Thanks very very very much for your suggestion. It worked fine for me.

Best wishes,
Changliang.
