### ISSUE TITLE
NameError: name 'CVM' is not defined

### ISSUE THREAD

**Issue by QianzhaoJ** [qinqian/lisa#8]
Hi,
I'm very interested in Lisa for transcriptional factors prediction, and I installed Lisa successfully using conda. But when I run Lisa using `lisa model --clean=True --method="all" --web=True --new_rp_h5=None --new_count_h5=None --species hg38 --epigenome "['DNase', 'H3K27ac']" --cluster=False --covariates=False --random=True --prefix RNAseq_down --background=None --stat_background_number=1000 --threads 24 /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt`, some error occurs:
`NameError: name 'CVM' is not defined
Error in job lisa_in_silico_knockout_motif_99 while creating output files /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.DNase.motif99.csv, /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.DNase.motif99.p_value.csv.
RuleException:
CalledProcessError in line 33 of /share/home/jiqianzhao/anaconda3/envs/lisa2/lib/python3.6/site-packages/lisa/rules/knockout.rule:
Command 'lisa_rank_tfs knockout --species hg38  --epigenome DNase --coefficient /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.DNase.coefs.csv --background /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.background_gene.1000 --foreground /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.foreground_gene --prefix /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt --dtype motif99  --covariates=False  --new_h5_rp=None --new_h5_count=None  --only_newhdf5=False >> /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.log ' returned non-zero exit status 1.
  File "/share/home/jiqianzhao/anaconda3/envs/lisa2/lib/python3.6/site-packages/lisa/rules/knockout.rule", line 33, in __rule_lisa_in_silico_knockout_motif_99
  File "/share/home/jiqianzhao/anaconda3/envs/lisa2/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Error in job lisa_in_silico_knockout_tf_chipseqpeak while creating output files /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.DNase.chipseq.csv, /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.DNase.chipseq.p_value.csv.
RuleException:
CalledProcessError in line 51 of /share/home/jiqianzhao/anaconda3/envs/lisa2/lib/python3.6/site-packages/lisa/rules/knockout.rule:
Command 'lisa_rank_tfs knockout --species hg38  --epigenome DNase --coefficient /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.DNase.coefs.csv --background /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.background_gene.1000 --foreground /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.foreground_gene --prefix /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt --dtype chipseq  --covariates=False  --new_h5_rp=None --new_h5_count=None  --only_newhdf5=False >> /share/home/jiqianzhao/05_Results/03_P4HB/geneset5/RNAseq_Down_Symbol.txt.log ' returned non-zero exit status 1.
  File "/share/home/jiqianzhao/anaconda3/envs/lisa2/lib/python3.6/site-packages/lisa/rules/knockout.rule", line 51, in __rule_lisa_in_silico_knockout_tf_chipseqpeak
  File "/share/home/jiqianzhao/anaconda3/envs/lisa2/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
`
What happened? Could you give me some suggestions?

Bests
Qianzhao

**Comment by qinqian** [comment]
Somehow this issue fell off my radar. I could not reproduce this without the input gene set and conda environment version information, please try our online version (http://lisa.cistrome.org/) and the latest command line version of lisa2 at https://github.com/liulab-dfci/lisa2/.
